apiVersion: v1
kind: Pod
metadata:
  annotations: 
    consul.hashicorp.com/connect-inject: "true"
    consul.hashicorp.com/connect-service-upstreams: "compote-server:8080"
  labels:
    run: compote-client
  name: compote-client
spec:
  containers:
  - image: docker.bc-artifactory01/k8s-docker/compote_client
    name: compote-client
    envFrom:
    - configMapRef:
       name: special-config
       optional: true