apiVersion: v1
kind: Service
metadata:
  labels:
    run: compote-client
  name: compote-client
spec:
  clusterIP: None
  selector:
    run: compote-client
  type: ClusterIP
--- 
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: compote-client
spec:
  protocol: http