apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: go-app
build:
  artifacts:
  - image: docker.bc-artifactory01/k8s-docker/compote_client
    context: client
    docker:
      dockerfile: Dockerfile
  - image: docker.bc-artifactory01/k8s-docker/compote_server
    context: server
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - client/k8s/configmap.yaml
    - client/k8s/pod.yaml
    - client/k8s/svc.yaml
    - server/k8s/pod.yaml
    - server/k8s/secret.yaml
    - server/k8s/svc.yaml
