apiVersion: v1
kind: Pod
metadata:
  labels:
    run: compote-server
  name: compote-server
spec:
  containers:
  - image: docker.bc-artifactory01/k8s-docker/compote_server
    name: compote-server
  imagePullSecrets:
  - name: regcred