apiVersion: v1
kind: Pod
metadata:
  annotations: 
    consul.hashicorp.com/connect-inject: "true"
  labels:
    run: compote-server
  name: compote-server
spec:
  containers:
  - image: docker.bc-artifactory01/k8s-docker/compote_server
    name: compote-server
    ports:
    - containerPort: 8080
  imagePullSecrets:
  - name: regcred