apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJkb2NrZXIuYmMtYXJ0aWZhY3RvcnkwMSI6eyJ1c2VybmFtZSI6Im1pY2hhZWwudmFyZWlraXMiLCJwYXNzd29yZCI6IlZhcjIwMjIhISIsImF1dGgiOiJiV2xqYUdGbGJDNTJZWEpsYVd0cGN6cFdZWEl5TURJeUlTRT0ifX19
kind: Secret
metadata:
  creationTimestamp: null
  name: regcred
type: kubernetes.io/dockerconfigjson
