apiVersion: v1
kind: Service
metadata:
  labels:
    run: compote-server
  name: compote-server
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: compote-server
  type: ClusterIP
